version: '3'
services:
        web:
                image: studybuddy
                build: .
                ports:
                        - "8029:8029"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
